# Generated by Django 4.1.5 on 2023-01-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_alter_product_id_alter_product_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to=''),
        ),
    ]
