# Generated by Django 4.1.5 on 2023-02-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_profile_image_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviwe',
            name='product',
        ),
        migrations.AddField(
            model_name='reviwe',
            name='product',
            field=models.ManyToManyField(to='base.product'),
        ),
    ]
